# Generated by Django 3.2.2 on 2021-06-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transacao_CNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(max_length=1)),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.FloatField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=12)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('dono_loja', models.CharField(max_length=14)),
                ('nome_loja', models.TextField(max_length=19)),
            ],
        ),
    ]
