# Generated by Django 3.2.2 on 2021-06-21 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo_txt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_hora_carga', models.DateTimeField(auto_now_add=True)),
                ('url', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transacao_CNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9)])),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.FloatField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=12)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('dono_loja', models.CharField(max_length=14)),
                ('nome_loja', models.TextField(max_length=19)),
            ],
        ),
    ]
